tango_with_django_project/rango/urls.py
from django.urls import path
from rango import views
from rango.views import *
app_name = 'rango'


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('category/<slug:category_name_slug>/', ShowCategoryView.as_view(), name='show_category'),
    path('add_category/', AddCategoryView.as_view(), name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', AddPageView.as_view(), name='add_page'),
    path('restricted/', views.restricted, name='restricted'),
    path('goto/', views.goto_page, name='goto'),
    path('register_profile/', RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<str:username>/', ProfileView.as_view(), name='profile'),
    path('users/', ListUsersView.as_view(), name='users'),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
    path('suggest/', views.CategorySuggestionView.as_view(), name='suggest'),
    path('search_add_page/', views.AddBingSearchPageView.as_view(), name='search_add_page'),
]

tango_with_django_project/tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView
from django.urls import reverse
from rango.views import IndexView


class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tango_with_django_project/rango/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.utils.timezone import now


# Create your models here.

# Model representing the Category containing a list of Pages
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        if self.views < 0:
            self.views = 0

        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


# Model representing a web page in the Rango app
class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    last_visited = models.DateTimeField(default=now, blank=True, null=True)

    def save(self, *args, **kwargs):
        if self.last_visited > now():
            self.last_visited = now()

        super(Page, self).save(*args, **kwargs)

    def __str__(self):
        return self.title


# User Profile
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

tango_with_django_project/rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Category, Page, UserProfile


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category._meta.get_field('name').max_length,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information for the form
    class Meta:
        # Provide association between ModelForm and a model
        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page._meta.get_field('title').max_length,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=Page._meta.get_field('url').max_length,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page

        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture',)

tango_with_django_project/rango/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from rango.models import Category, Page, UserProfile
from django.contrib.auth.models import User
from django.utils.decorators import method_decorator
from rango.forms import CategoryForm, PageForm, UserProfileForm
from django.views.generic import TemplateView
from datetime import datetime
from rango.bing_search import BingSearch
from django.http import HttpResponse
from django.utils.timezone import now


class IndexView(TemplateView):

    def get(self, request):
        # Query the database for a list of ALL categories currently stored.
        # Order the categories by the number of likes in descending order.
        # Retrieve the top 5 only -- or all if less than 5.
        # Place the list in our context_dict dictionary (with our boldmessage!)
        # that will be passed to the template engine.
        category_list = Category.objects.order_by('-likes')[:5]

        # list with top 5 most viewed pages
        pages_list = Page.objects.order_by('-views')[:5]

        context_dict = dict()
        context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
        context_dict['categories'] = category_list
        context_dict['pages'] = pages_list

        # Helper function to handle cookies
        visitor_cookie_handler(request)

        return render(request, 'rango/index.html', context=context_dict)


class AboutView(TemplateView):

    def get(self, request):
        context_dict = {'boldmessage': 'Kristiyan Ivanov'}

        visitor_cookie_handler(request)
        context_dict['visits'] = request.session['visits']

        return render(request, 'rango/about.html', context=context_dict)


class ShowCategoryView(TemplateView):

    def generate_context_dict(self, category_name_slug):
        context_dict = dict()

        try:
            category = Category.objects.get(slug=category_name_slug)
            pages = Page.objects.filter(category=category).order_by('-views')
            context_dict['category'] = category
            context_dict['pages'] = pages

        except Category.DoesNotExist:
            context_dict['category'] = None
            context_dict['pages'] = None

        return context_dict

    def get(self, request, category_name_slug):
        context_dict = self.generate_context_dict(category_name_slug)
        return render(request, 'rango/category.html', context=context_dict)

    def post(self, request, category_name_slug):
        context_dict = self.generate_context_dict(category_name_slug)

        query = request.POST['query'].strip()
        results = BingSearch.run_query(query)
        context_dict['query'] = query
        context_dict['result_list'] = results

        return render(request, 'rango/category.html', context=context_dict)


class CategorySuggestionView(TemplateView):

    def get(self, request):
        if 'suggestion' in request.GET:
            suggestion = request.GET['suggestion']
        else:
            suggestion = ''

        category_list = get_category_list(max_results=8, starts_with=suggestion)

        if len(category_list) == 0:
            category_list = Category.objects.order_by('-likes')

        return render(request, 'rango/categories.html', {'categories': category_list})


def get_category_list(max_results=0, starts_with=''):
    category_list = []
    if starts_with:
        category_list = Category.objects.filter(name__istartswith=starts_with)
    if max_results > 0:
        if len(category_list) > max_results:
            category_list = category_list[:max_results]

    return category_list


class AddCategoryView(TemplateView):

    @method_decorator(login_required)
    def get(self, request):
        form = CategoryForm()
        return render(request, 'rango/add_category', {'form': form})

    @method_decorator(login_required)
    def post(self, request):
        form = CategoryForm(request.POST)

        if form.is_valid():
            cat = form.save(commit=True)

            # confirmation that the category is added
            print(cat, cat.slug)

            return redirect(reverse('rango:index'))
        else:
            # print form contained errors to the terminal
            print(form.errors)

        return render(request, 'rango/add_category.html', {'form': form})


class LikeCategoryView(TemplateView):

    @method_decorator(login_required)
    def get(self, request):
        category_id = request.GET['category_id']
        try:
            category = Category.objects.get(id=int(category_id))
        except Category.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)

        category.likes = category.likes + 1
        category.save()
        return HttpResponse(category.likes)


class AddPageView(TemplateView):

    def get_category(self, category_name_slug):
        try:
            return Category.objects.get(slug=category_name_slug)

        except Category.DoesNotExist:
            return None

    @method_decorator(login_required)
    def get(self, request, category_name_slug):
        category = self.get_category(category_name_slug)

        if category is None:
            return redirect(reverse('rango:index'))

        form = PageForm()

        return render(request, 'rango/add_page.html', {'form': form, 'category': category})

    @method_decorator(login_required)
    def post(self, request, category_name_slug):
        category = self.get_category(category_name_slug)

        if category is None:
            return redirect(reverse('rango:index'))

        form = PageForm(request.POST)

        if form.is_valid():
            page = form.save(commit=False)
            page.category = category
            page.views = 0
            page.save()

            return redirect(reverse('rango:show_category',
                                    kwargs={'category_name_slug': category_name_slug}))
        else:
            print(form.errors)


class RegisterProfileView(TemplateView):

    @method_decorator(login_required)
    def get(self, request):
        form = UserProfileForm()
        return render(request, 'rango/profile_registration.html', {'form': form})

    @method_decorator(login_required)
    def post(self, request):
        form = UserProfileForm(request.POST, request.FILES)

        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            # confirmation that the category is added
            print(user_profile.user.username)

            return redirect(reverse('rango:index'))
        else:
            # print form contained errors to the terminal
            print(form.errors)

        return render(request, 'rango/profile_registration.html', {'form': form})


class ProfileView(TemplateView):

    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({
            'website': user_profile.website,
            'picture': user_profile.picture
        })

        return user, user_profile, form

    @method_decorator(login_required)
    def get(self, request, username):
        context_dict = dict()
        try:
            user, user_profile, form = self.get_user_details(username)

            context_dict = {
                'user_profile': user_profile,
                'selected_user': user,
                'form': form
            }
        except TypeError:
            redirect(reverse('rango:index'))

        return render(request, 'rango/profile.html', context_dict)

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            user, user_profile, form = self.get_user_details(username)
        except TypeError:
            redirect(reverse('rango:index'))

        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('rango:profile', kwargs={'username': username}))

        context_dict = {
            'user_profile': user_profile,
            'selected_user': user,
            'form': form
        }

        return render(request, 'rango/profile.html', context_dict)


class ListUsersView(TemplateView):

    def get(self, request):
        users = UserProfile.objects.filter(user__is_staff=False).order_by('user__username')
        context_dict = {'users': users}

        return render(request, 'rango/users.html', context_dict)


class AddBingSearchPageView(TemplateView):

    @method_decorator(login_required)
    def get(self, request):
        url = request.GET['page_url']
        title = request.GET['title']
        category_id = request.GET['category_id']

        try:
            category = Category.objects.get(id=int(category_id))
        except Category.DoesNotExist:
            return HttpResponse('Error - category not found.')

        page, just_created = Page.objects.get_or_create(url=url, category=category)
        if just_created:
            page.title = title
            page.save()

        pages = Page.objects.filter(category_id=category_id).order_by('-views')
        return render(request, 'rango/list_pages.html', {'pages': pages})


def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val

    return val


# wrapper view used to track external redirects
def goto_page(request):
    page_id = request.GET.get('page_id')

    try:
        selected_page = Page.objects.get(id=page_id)
    except Page.DoesNotExist:
        return redirect(reverse('rango:index'))

    selected_page.views = selected_page.views + 1

tango_with_django_project/templates/rango/about.html
{% extends 'rango/base.html' %}
{% load static %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container-fluid">
        <h1 class="jumbotron-heading">About Rango</h1>
    </div>
</div>
<div>
    <p>Visits: {{ visits }}</p>
    here is the about page. <br/>
    <strong>this website has been put together by {{ boldmessage }}.</strong><br/>
</div>
<div>
    <button class="btn btn-primary"
        onclick="alert('You clicked the button using inline JavaScript.');">
    Click me - I run on vanilla JavaScript!
</button>
</div><br>
<div>
    <button class="btn btn-primary" id="about-btn">
        Click me - I'm using JQuery!
    </button>
</div><br>
<p id="para_id">
    This is some text for the JQuery example.
</p>
<div id="msg">Hello! I'm a further example for JQuery testing.</div>
<div>
    <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango"/>
</div>
<div>
    <img src="{{ MEDIA_URL }}cat.jpeg"
         alt="Picture of Dog"/>
</div>

{% endblock %}

tango_with_django_project/templates/rango/add_category.html
{% extends "rango/base.html" %}
{% block title %}Add Category{% endblock %}
{% block body_block %}
<div class="jumbotron p-4">
    <div class="container-fluid">
        <h1 class="jumbotron-heading">Add a Category</h1>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br>
                {{ field }}<br>
                <div class="p-2"></div>
            {% endfor %}
            <br/>
            <button class="btn btn-primary" type="submit" name="submit">
                Add Category
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

tango_with_django_project/templates/rango/add_page.html
{% extends "rango/base.html" %}
{% block title %}Add Page{% endblock %}
{% block body_block %}
<div class="jumbotron p-4">
    <div class="container-fluid">
        <h1 class="jumbotron-heading">Add a Page to {{category.name}}</h1>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <form role="form" id="page_form" method="post"
              action="{% url 'rango:add_page' category.slug %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}

            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br/>
                {{ field }}<br/>
                <div class="p-2"></div>
            {% endfor %}
            <br/>
            <button class="btn btn-primary" type="submit" name="submit">
                Add Page
            </button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

tango_with_django_project/templates/rango/base-old.html
<!DOCTYPE html>
{% load static %}
{% load rango_template_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Rango - {% block title_block %} How to Tango with Django! {% endblock %}</title>
</head>
<body>
    <div>
        {% block body_block %}
        {% endblock %}
    </div>
    <div>
        {% block sidebar_block %}
            {% get_category_list category %}
        {% endblock %}
    </div>
    <hr />
    <div>
        <ul>
            {% if user.is_authenticated %}
            <!-- Show these links when the user is logged in -->
            <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
            <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
            <li><a href="{% url 'auth_password_change' %}?next={% url 'auth_password_change_done'%}">Change Password</a></li>
            <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
            {% else %}
            <!-- Show these links when the user is NOT logged in -->
            <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
            <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
            <!-- Outside the conditional statements, ALWAYS show -->
            <li><a href="{% url 'rango:about' %}">About</a></li>
            <li><a href="{% url 'rango:index' %}">Index</a></li>
        </ul>
    </div>
</body>
</html>

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Kristiyan Ivanov">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">

    {% block scripts %}
        <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/rango-jquery.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/rango-ajax.js' %}" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    {% endblock %}

    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:users' %}">Users</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                        {% endif %}
                    </ul>
                    <ul class="navbar-nav">
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        {% else %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>

        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="w-75 ml-3">
                        <input type="search"
                        id="search-input"
                        class="form-control ds-input"
                        placeholder="Search..." />
                    </div>

                    <div class="sidebar-sticky" id="categories-listing">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>

                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                    {% block body_block %}
                    {% endblock %}

                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 Tango With Django 2 <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>
    </body>
</html>

tango_with_django_project/templates/rango/categories.html
<ul class="nav flex-column">
{% if categories %}
    {% for c in categories%}
        {% if c == current_category %}
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
            <span data-feather="archive"></span>{{ c.name }}
            </a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
                <span data-feather="archive"></span>{{ c.name }}
            </a>
        </li>
        {% endif %}
    {% endfor %}
{% else %}
<li class="nav-item">There are no categories present.</li>
{% endif %}
</ul>

tango_with_django_project/templates/rango/category.html
{% extends 'rango/base.html' %}
{% load static %}
{% load rango_template_tags %}

{% block body_block %}
{% if category %}
<div class="jumbotron p-4">
    <div class="container-fluid">
        <h1 class="jumbotron-heading">{{ category.name }}</h1>
        <div>
            <strong id="like_count">{{ category.likes }}</strong> likes
            {% if user.is_authenticated %}
            <button id="like_btn" data-categoryid="{{ category.id }}" class="btn btn-primary btn-sm" type="button">
                <span data-feather="thumbs-up"></span>
                Like Category
            </button>
            {% endif %}
        </div>
    </div>
</div>
<div>
    <div id="list_pages">
        {% get_pages_list category.id %}
    </div>

    {% if user.is_authenticated %}
        <div>
            <p><strong>You don't find the page you need? Here, search the web for it.</strong></p>
            <form class="form-inline" id="user-form" method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <input class="form-control" type="text" size="50" name="query" id="query_id"
                           value="{{ query }}">
                    <button class="btn btn-primary" type="submit" name="submit">
                    Search
                    </button>
                </div>
            </form>
        </div>
        <div>
            {% if result_list %}
                <br>
                <h2>Results</h2>
                <div class="list-group">
                    {% for result in result_list %}
                        <div class="list-group-item">
                            <h3 class="list-group-item-heading">
                                <a href="{{ result.link }}">
                                    {{ result.title|safe|escape }}
                                </a>
                                <a type="button" class="btn btn-info btn-sm search-page-add"
                                   data-url="{{ result.link }}"
                                   data-title="{{ result.title }}"
                                   data-categoryid="{{ category.id }}">Add</a>
                            </h3>
                            <p class="list-item-group-text">
                                {{ result.summary|safe|escape }}
                            </p>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    {% endif %}
</div>
{% else %}
The specific category does not exist.
{% endif %}
{% endblock %}

tango_with_django_project/templates/rango/index.html
{% extends 'rango/base.html' %}
{% load static %}

{% block title_block %}
Homepage
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4">
    <div class="container-fluid">
        <h1 class="jumbotron-heading">Rango says...</h1>
        <div>
            <h2 class="h2">
                {% if user.is_authenticated %}
                howdy {{ user.username }}!
                {% else %}
                hey there partner!
                {% endif %}
            </h2>
            <strong>{{ boldmessage }}</strong>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Most Liked Categories</h2>
                    <p class="card-text">
                        {% if categories %}
                    <ul class="list-group">
                        {% for category in categories %}
                        <li class="list-group-item">
                            <a href="{% url 'rango:show_category' category.slug %}">
                                {{ category.name }}</a>
                            <span class="badge badge-primary text-wrap">
                                {{ category.likes }} like{{ category.likes|pluralize }}
                            </span>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <strong>There are no categories present.</strong>
                    {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card mb-6">
                <div class="card-body">
                    <h2>Most Viewed Pages</h2>
                    <p class="card-text">
                        {% if pages %}
                    <ul class="list-group">
                        {% for page in pages %}
                        <li class="list-group-item">
                            <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                            <span class="badge badge-primary text-wrap">
                                {{ page.views }} view{{ page.views|pluralize }}
                            </span>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <strong>There are no pages present.</strong>
                    {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tango_with_django_project/templates/rango/list_pages.html
{% if pages %}
    <ul>
        {% for page in pages %}
        <li>
            <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
            <span class="badge badge-primary text-wrap">
                {{ page.views }} view{{ page.views|pluralize }}
            </span>
        </li>
        {% endfor %}
    </ul>
{% else %}
    <strong>No pages found!</strong> <br>
{% endif %}